spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=mydatabase;encrypt=true;trustServerCertificate=true
    username: SA
    password: Quan#1812@2000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
      repositories:
        enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: homanhquan1812@gmail.com
    password: srwldxzocvqetzgu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000

  jackson:
    deserialization:
      fail-on-unknown-properties: false

async:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    thread-name-prefix: "Async-Email-"
    keep-alive-seconds: 60
    allow-core-thread-timeout: true
    await-termination-seconds: 60

jwt:
  secret: Z4uT3x9pR2mF8aC7yWqK5nD1vB6sL0hJtP3rX8cE2qY9zG4wM1fV7oU5jN6iT0
  expiration: 86400000

app:
  email:
    from-email: homanhquan1812@gmail.com
    from-name: HMQ Cake Shop

logging:
  level:
    root: INFO
    org.homanhquan.product-service: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF