spring:
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=mydatabase
    username: sa
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
# Test
  redis:
    repositories:
      enabled: false

  rabbitmq:
    listener:
      simple:
        auto-startup: false

  mail:
    host: localhost

# Change
jwt:
  secret: test-secret-key-test-secret-key-test-secret
  expiration: 86400000
