package org.homanhquan.productservice.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.homanhquan.productservice.entity.common.Auditable;
import org.homanhquan.productservice.enums.Status;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Annotation/Method definition:
 * - @Data: Includes @Getter, @Setter, @ToString, @EqualsAndHashCode, and @RequiredArgsConstructor.
 *   NOT RECOMMENDED because:
 *   + @ToString may trigger lazy loading (N + 1 problems) and leak sensitive data in logs (id, password, token, etc).
 *     Use @ToString(exclude = {"relationship", "password"}) if needed.
 *   + @EqualsAndHashCode may cause unexpected behavior with JPA proxies and relationships.
 *   + @RequiredArgsConstructor conflicts with @NoArgsConstructor.
 *
 * - @Builder: An annotation that implements the Builder design pattern, allowing you to create objects step by step with a fluent, readable API instead of using long constructors.
 *   NOT RECOMMENDED because:
 *   + Requires @AllArgsConstructor to work -> Conflicts with @NoArgsConstructor.
 *   + Not suitable for entities that are frequently updated.
 *
 * - @Index: Defines a database index on one or more table columns to improve query performance, especially for search and filtering operations.
 *   NOT RECOMMENDED because Index definitions should be managed at the database or migration level (Flyway/Liquibase), not in entities.
 *
 * - @Entity: Marks a Java class as a persistent entity, meaning it is mapped to a database table and managed by the ORM framework.
 *
 * - @Table(name = "???"): Table's name.
 *
 * - @Getter: Generates getter methods for all fields.
 *
 * - @Setter: Generates setter methods for all non-final fields (PUBLIC by default).
 *   @Setter(AccessLevel.NONE): Prevents this field from adjusting outside.
 *
 * - @NoArgsConstructor: A constructor with zero parameters. Required by JPA/Hibernate for entity instantiation via reflection.
 *
 * - @Id: Primary key.
 *
 * - @GeneratedValue: Specifies that the value of the primary key will be automatically generated by the persistence provider (e.g., Hibernate).
 *
 * - @Column: Maps a class field to a database table column and to configure column details.
 *   + name = address -> Schema's field name.
 *   + updatable = false -> Value can't be changed.
 *   + nullable = false -> Value can't be null.
 *   + unique = true -> Value must be unique.
 *   + length = 10 -> Maximum text length of value (Only for String) -> NOT COMMON compared to @Size.
 *   + columnDefinition = "TEXT" -> Column data type in database: TEXT (Mostly no need to use it).
 *   + precision = 10 -> Total number of digits stored (BigDecimal).
 *   + scale = 2 -> The number of digits after the decimal point (BigDecimal).
 *
 * - @Enumerated(EnumType.STRING): Enums with String type.
 *
 * - @DecimalMin(value = "0.0", inclusive = false): Validate that a numeric value is greater than or equal to a specified minimum decimal value:
 *   + If inclusive = false, numbers like 0.00, 0.0000 or less than 0 are not allowed.
 *   + If inclusive = true, numbers like 0.00, 0.0000 are allowed, still less than 0 are not allowed.
 * - @Size: Validate the size or length of a value, such as strings, collections, maps, or arrays, by specifying minimum and/or maximum limits:
 *   + min = 5 -> Minimum text length of value.
 *   + max = 10 -> Maximum text length of value.
 * ==================================================
 * Notes:
 * - Entity shouldn't have validations such as @NotBlank, @NotNull, @NotEmpty, they are mostly for DTO.
 *   Better only keep database constraints here.
 * - Which type of ID to choose?
 *   + IDENTITY (Long/Integer): Auto-increment ID.
 *     (+): Simple, easy to use, and widely supported across databases (MySQL, PostgreSQL, MSSQL).
 *     (-): Poor performance with batch inserts & Not suitable for distributed systems.
 *     (?): When to use - Small to medium apps, single database.
 *     -> @GeneratedValue(strategy = GenerationType.IDENTITY)
 *   + UUID (UUID): Universally Unique Identifier that is used to uniquely identify information across systems, with an extremely low chance of duplication.
 *     (+): Globally unique.
 *     (-): Large storage size (16 bytes).
 *     (?): When to use - Distributed system, microservices.
 *     v4: Random ID -> No sorting -> Poor index performance.
 *     -> @GeneratedValue(strategy = GenerationType.UUID)
 *        @Column(columnDefinition = "UNIQUEIDENTIFIER")
 *     v7: Time-ordered ID based on timestamps -> Good sorting -> Better index performance.
 *     -> @GeneratedValue(strategy = GenerationType.UUID)
 *        @UuidGenerator(style = UuidGenerator.Style.TIME)
 *        @Column(columnDefinition = "UNIQUEIDENTIFIER")
 *  + ULID (String): Universally Unique Lexicographically Sortable Identifier that includes a timestamp, making it sortable by creation time and efficient for database indexing.
 *    (+) Time-ordered, URL-safe, case-insensitive, shorter than UUID when string-encoded.
 *    (-): Less common, requires external library.
 *    (?) When to use - When you need sortable IDs in string format.
 *    -> @PrePersist
 *       protected void onCreate() {
 *          this.id = UlidCreator.getUlid().toString();
 *       }
 *  + SEQUENCE (Long): Generates ordered, incremental numbers, commonly used for auto‑generating primary keys in a safe and scalable way.
 *    (+): Good performance with batch inserts (pre-allocates IDs).
 *    (-): Not portable across databases (MySQL > 8.0, MSSQL > 12, etc).
 *    (?): When to use - Internal IDs, business-defined numbering.
 *    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "product_seq")
 *    @SequenceGenerator(
 *            name = "product_seq",
 *            sequenceName = "product_sequence",
 *            initialValue = 10000001,  // Start from here
 *            allocationSize = 1        // Increase by 1
 *    )
 */
@Entity
@Table(name = "product")
@Getter
@Setter
@NoArgsConstructor
public class Product extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", columnDefinition = "UNIQUEIDENTIFIER", updatable = false, nullable = false)
    @Setter(AccessLevel.NONE)
    private Long id;

    @Size(min = 1, max = 50, message = "Name must be between 1 and 50 characters")
    @Column(name = "name", nullable = false)
    private String name;

    @Column(name = "description", nullable = false)
    private String description;

    @Enumerated(EnumType.STRING)
    @Size(min = 1, max = 10, message = "Status must be between 1 and 10 characters")
    @Column(name = "status", nullable = false)
    private Status status;

    @DecimalMin(value = "0.0", inclusive = false, message = "Price must be greater than 0")
    @Digits(integer = 16, fraction = 2, message = "Price format is invalid")
    @Column(name = "price", nullable = false, precision = 18, scale = 2)
    private BigDecimal price;

    @Column(name = "created_by", updatable = false)
    private UUID createdBy;

    @Column(name = "updated_by")
    private UUID updatedBy;

    @Column(name = "deleted_by")
    private UUID deletedBy;

    // Manual equals() & hashCode()
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Product other)) return false;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    /**
     * Relationship -> USE IT WITH CAUTIONS because:
     * - Collection relationships easily cause N+1 and performance issues.
     * - LAZY without fetch join easily leads to N+1 queries.
     * - Cascading with soft delete is error-prone.
     * There are 2 deletion types:
     * - Soft-delete (CascadeType.PERSIST: Create, CascadeType.MERGE: Update).
     * - Hard-delete: cascade = CascadeType.ALL, orphanRemoval = true.
     * By default:
     * - @OneToOne & @ManyToOne: FetchType.EAGER -> Loads all related entities immediately, even not necessary -> Better set LAZY.
     * - @OneToMany & @ManyToMany: FetchType.LAZY.
     * ==================================================
     * N+1 problems occur when an application executes 1 query to fetch a list of entities and then N additional queries to fetch related data for each entity.
     * This leads to N+1 total queries instead of 1 optimized join query, causing performance issues.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brand_id", nullable = false)
    private Brand brand;
}
