name: Spring Boot CI (SQL Server + Redis + RabbitMQ)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # -------------------------------
      # SQL Server
      # -------------------------------
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1434:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SQLSERVER_SA_PASSWORD }}
          MSSQL_MEMORY_LIMIT_MB: 2048
        options: >-
          --health-cmd "/bin/bash -c \"/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \\\"$SA_PASSWORD\\\" -Q 'SELECT 1' || exit 1\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15
          --health-start-period 90s
      
      

      # -------------------------------
      # Redis
      # -------------------------------
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      # -------------------------------
      # RabbitMQ
      # -------------------------------
      rabbitmq:
        image: rabbitmq:3.12-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # -------------------------------
      # Inject environment variables
      # -------------------------------
      - name: Set env for Spring Boot
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:sqlserver://localhost:1434;databaseName=mydatabase;encrypt=true;trustServerCertificate=true" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=sa" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SQLSERVER_SA_PASSWORD }}" >> $GITHUB_ENV

          echo "SPRING_REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "SPRING_REDIS_PORT=6379" >> $GITHUB_ENV

          echo "SPRING_RABBITMQ_HOST=localhost" >> $GITHUB_ENV
          echo "SPRING_RABBITMQ_PORT=5672" >> $GITHUB_ENV
          echo "SPRING_RABBITMQ_USERNAME=guest" >> $GITHUB_ENV
          echo "SPRING_RABBITMQ_PASSWORD=guest" >> $GITHUB_ENV

          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Build & Test
        run: mvn -B clean verify

      - name: Upload JAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: product-service
          path: target/*.jar
